//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusWeb.Code.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_viplist
    {
        public int ACCOUNT_ID { get; set; }
        public byte WORLD_ID { get; set; }
        public int PLAYER_ID { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual players players { get; set; }
    }
}
