//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusWeb.Code.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_deaths
    {
        public int ID { get; set; }
        public int PLAYER_ID { get; set; }
        public decimal DATE { get; set; }
        public long LEVEL { get; set; }
    
        public virtual players players { get; set; }
    }
}
